"""Initial migration

Revision ID: d2243e91d0ad
Revises: 
Create Date: 2026-05-29 18:31:34.324201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2243e91d0ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('couleurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couleurs_id'), 'couleurs', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('statuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statuts_id'), 'statuts', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.create_table('sous_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sous_categories_id'), 'sous_categories', ['id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('marques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('souscategorie_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['souscategorie_id'], ['sous_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marques_id'), 'marques', ['id'], unique=False)
    op.create_table('titres_objets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['sous_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titres_objets_id'), 'titres_objets', ['id'], unique=False)
    op.create_table('objets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('souscategorie_id', sa.Integer(), nullable=True),
    sa.Column('marque_id', sa.Integer(), nullable=True),
    sa.Column('couleur_id', sa.Integer(), nullable=True),
    sa.Column('statut_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_action', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('recompense', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['couleur_id'], ['couleurs.id'], ),
    sa.ForeignKeyConstraint(['marque_id'], ['marques.id'], ),
    sa.ForeignKeyConstraint(['souscategorie_id'], ['sous_categories.id'], ),
    sa.ForeignKeyConstraint(['statut_id'], ['statuts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objets_id'), 'objets', ['id'], unique=False)
    op.create_table('images_objets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['objet_id'], ['objets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_objets_id'), 'images_objets', ['id'], unique=False)
    op.create_table('modifications_objets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objet_id', sa.Integer(), nullable=True),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['objet_id'], ['objets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifications_objets_id'), 'modifications_objets', ['id'], unique=False)
    op.drop_index(op.f('objets_marque_souscategorie_id_d52eebf5'), table_name='objets_marque')
    op.drop_table('objets_marque')
    op.drop_table('django_migrations')
    op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.drop_index(op.f('auth_permission_content_type_id_2f476e4b'), table_name='auth_permission')
    op.drop_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('django_admin_log_content_type_id_c4bce8eb'), table_name='django_admin_log')
    op.drop_index(op.f('django_admin_log_user_id_c564eba6'), table_name='django_admin_log')
    op.drop_table('django_admin_log')
    op.drop_table('auth_group')
    op.drop_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), table_name='auth_user_user_permissions')
    op.drop_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index(op.f('objets_souscategorie_categorie_id_e39d754a'), table_name='objets_souscategorie')
    op.drop_table('objets_souscategorie')
    op.drop_table('objets_categorie')
    op.drop_index(op.f('auth_user_groups_group_id_97559544'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_6a12ed8b'), table_name='auth_user_groups')
    op.drop_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index(op.f('objets_imageobjet_object_id_faf58672'), table_name='objets_imageobjet')
    op.drop_table('objets_imageobjet')
    op.drop_table('auth_user')
    op.drop_index(op.f('objets_modifierobjet_objet_id_6361d8d0'), table_name='objets_modifierobjet')
    op.drop_table('objets_modifierobjet')
    op.drop_table('objets_statut')
    op.drop_table('objets_couleur')
    op.drop_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index(op.f('objets_objet_categorie_id_6e33a200'), table_name='objets_objet')
    op.drop_index(op.f('objets_objet_couleur_id_cd8a6eac'), table_name='objets_objet')
    op.drop_index(op.f('objets_objet_marque_id_f1486722'), table_name='objets_objet')
    op.drop_index(op.f('objets_objet_souscategorie_id_afafcb58'), table_name='objets_objet')
    op.drop_index(op.f('objets_objet_statut_id_4f69a157'), table_name='objets_objet')
    op.drop_table('objets_objet')
    op.drop_index(op.f('auth_group_permissions_group_id_b120cbf9'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), table_name='auth_group_permissions')
    op.drop_index(op.f('auth_group_permissions_permission_id_84c5c92e'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('objets_titreobjet_type_id_1381bf83'), table_name='objets_titreobjet')
    op.drop_table('objets_titreobjet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objets_titreobjet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['objets_souscategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_titreobjet_type_id_1381bf83'), 'objets_titreobjet', ['type_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_group_permissions_permission_id_84c5c92e'), 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_group_permissions_group_id_b120cbf9'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('objets_objet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('date_action', sa.DATE(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('categorie_id', sa.BIGINT(), nullable=True),
    sa.Column('couleur_id', sa.BIGINT(), nullable=True),
    sa.Column('marque_id', sa.BIGINT(), nullable=True),
    sa.Column('souscategorie_id', sa.BIGINT(), nullable=True),
    sa.Column('statut_id', sa.BIGINT(), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('lieu', sa.VARCHAR(length=255), nullable=False),
    sa.Column('recompense', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['objets_categorie.id'], ),
    sa.ForeignKeyConstraint(['couleur_id'], ['objets_couleur.id'], ),
    sa.ForeignKeyConstraint(['marque_id'], ['objets_marque.id'], ),
    sa.ForeignKeyConstraint(['souscategorie_id'], ['objets_souscategorie.id'], ),
    sa.ForeignKeyConstraint(['statut_id'], ['objets_statut.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_objet_statut_id_4f69a157'), 'objets_objet', ['statut_id'], unique=False)
    op.create_index(op.f('objets_objet_souscategorie_id_afafcb58'), 'objets_objet', ['souscategorie_id'], unique=False)
    op.create_index(op.f('objets_objet_marque_id_f1486722'), 'objets_objet', ['marque_id'], unique=False)
    op.create_index(op.f('objets_objet_couleur_id_cd8a6eac'), 'objets_objet', ['couleur_id'], unique=False)
    op.create_index(op.f('objets_objet_categorie_id_6e33a200'), 'objets_objet', ['categorie_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=1)
    op.create_table('objets_couleur',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets_statut',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets_modifierobjet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('change', sa.TEXT(), nullable=False),
    sa.Column('confirm', sa.BOOLEAN(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('objet_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['objet_id'], ['objets_objet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_modifierobjet_objet_id_6361d8d0'), 'objets_modifierobjet', ['objet_id'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets_imageobjet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('object_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objets_objet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_imageobjet_object_id_faf58672'), 'objets_imageobjet', ['object_id'], unique=False)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), 'auth_user_groups', ['user_id', 'group_id'], unique=1)
    op.create_index(op.f('auth_user_groups_user_id_6a12ed8b'), 'auth_user_groups', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_groups_group_id_97559544'), 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('objets_categorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets_souscategorie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('categorie_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['objets_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_souscategorie_categorie_id_e39d754a'), 'objets_souscategorie', ['categorie_id'], unique=False)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=1)
    op.create_index(op.f('auth_user_user_permissions_user_id_a95ead1b'), 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('auth_user_user_permissions_permission_id_1fbb5f2c'), 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', sa.INTEGER(), nullable=False),
    sa.Column('change_message', sa.TEXT(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_time', sa.DATETIME(), nullable=False),
    sa.CheckConstraint('"action_flag" >= 0'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('django_admin_log_user_id_c564eba6'), 'django_admin_log', ['user_id'], unique=False)
    op.create_index(op.f('django_admin_log_content_type_id_c4bce8eb'), 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), 'auth_permission', ['content_type_id', 'codename'], unique=1)
    op.create_index(op.f('auth_permission_content_type_id_2f476e4b'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objets_marque',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('souscategorie_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['souscategorie_id'], ['objets_souscategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('objets_marque_souscategorie_id_d52eebf5'), 'objets_marque', ['souscategorie_id'], unique=False)
    op.drop_index(op.f('ix_modifications_objets_id'), table_name='modifications_objets')
    op.drop_table('modifications_objets')
    op.drop_index(op.f('ix_images_objets_id'), table_name='images_objets')
    op.drop_table('images_objets')
    op.drop_index(op.f('ix_objets_id'), table_name='objets')
    op.drop_table('objets')
    op.drop_index(op.f('ix_titres_objets_id'), table_name='titres_objets')
    op.drop_table('titres_objets')
    op.drop_index(op.f('ix_marques_id'), table_name='marques')
    op.drop_table('marques')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_sous_categories_id'), table_name='sous_categories')
    op.drop_table('sous_categories')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_statuts_id'), table_name='statuts')
    op.drop_table('statuts')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_couleurs_id'), table_name='couleurs')
    op.drop_table('couleurs')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
