import type { AdminResourceConfig } from '@/types/api';

export const ADMIN_RESOURCES: AdminResourceConfig[] = [
  {
    key: 'users',
    label: 'Utilisateurs',
    subtitle: 'Gestion des comptes utilisateurs',
    endpoint: '/rbac/users',
    creatable: false,
    editable: true,
    deletable: true,
    fields: [
      { name: 'username', label: 'Nom d\'utilisateur', type: 'text', required: true },
      { name: 'email', label: 'Email', type: 'text', required: true },
      { name: 'is_active', label: 'Actif', type: 'boolean' },
      { name: 'is_superuser', label: 'Super utilisateur', type: 'boolean' },
      { name: 'commissariat_id', label: 'Commissariat', type: 'select', optionsKey: 'commissariats' },
    ],
    deletePath: (id) => `/rbac/users/${id}`,
  },
  {
    key: 'roles',
    label: 'Roles',
    subtitle: 'Gestion des rôles et permissions',
    endpoint: '/rbac/roles',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    deletePath: (id) => `/rbac/roles/${id}`,
  },
  {
    key: 'categories',
    label: 'Categories',
    subtitle: 'Classement principal des objets',
    endpoint: '/categories',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true, placeholder: 'Ex: Electronique' },
      { name: 'description', label: 'Description', type: 'textarea', placeholder: 'Description' },
    ],
    deletePath: (id) => `/categories/${id}`,
  },
  {
    key: 'sous-categories',
    label: 'Sous-categories',
    subtitle: 'Rattachement des categories',
    endpoint: '/sous-categories',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'categorie_id', label: 'Categorie parente', type: 'select', required: true, optionsKey: 'categories' },
    ],
    deletePath: (id) => `/sous-categories/${id}`,
  },
  {
    key: 'marques',
    label: 'Marques',
    subtitle: 'Marques rattachées aux sous-categories',
    endpoint: '/marques',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'souscategorie_id', label: 'Sous-categorie', type: 'select', required: true, optionsKey: 'sousCategories' },
    ],
    deletePath: (id) => `/marques/${id}`,
  },
  {
    key: 'couleurs',
    label: 'Couleurs',
    subtitle: 'Palette métier',
    endpoint: '/couleurs',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    deletePath: (id) => `/couleurs/${id}`,
  },
  {
    key: 'statuts',
    label: 'Statuts',
    subtitle: 'Etats des objets',
    endpoint: '/statuts',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    deletePath: (id) => `/statuts/${id}`,
  },
  {
    key: 'titres',
    label: 'Titres objets',
    subtitle: 'Intitules liés aux sous-categories',
    endpoint: '/titres-objets',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'type_id', label: 'Sous-categorie type', type: 'select', required: true, optionsKey: 'sousCategories' },
    ],
    deletePath: (id) => `/titres-objets/${id}`,
  },
  {
    key: 'objets',
    label: 'Objets',
    subtitle: 'Déclarations enregistrées',
    endpoint: '/objets?is_public=false',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'categorie_id', label: 'Categorie', type: 'select', optionsKey: 'categories' },
      { name: 'souscategorie_id', label: 'Sous-categorie', type: 'select', optionsKey: 'sousCategories' },
      { name: 'marque_id', label: 'Marque', type: 'select', optionsKey: 'marques' },
      { name: 'couleur_id', label: 'Couleur', type: 'select', optionsKey: 'couleurs' },
      { name: 'statut_id', label: 'Statut', type: 'select', required: true, optionsKey: 'statuts' },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'date_action', label: 'Date', type: 'date', required: true },
      { name: 'lieu', label: 'Lieu', type: 'text' },
      { name: 'contact_phone', label: 'Téléphone', type: 'text' },
      { name: 'contact_email', label: 'Email', type: 'text' },
      { name: 'recompense', label: 'Recompense', type: 'text' },
      { name: 'is_public', label: 'Public', type: 'boolean' },
    ],
    deletePath: (id) => `/objets/${id}`,
  },
  {
    key: 'images',
    label: 'Images',
    subtitle: 'Fichiers liés aux objets',
    endpoint: '/images',
    creatable: true,
    editable: false,
    deletable: true,
    fields: [
      { name: 'objet_id', label: 'Objet', type: 'select', required: true, optionsKey: 'objets' },
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'caption', label: 'Legende', type: 'text' },
      { name: 'image_url', label: 'Image', type: 'image', required: true, helperText: 'Choisir une image depuis la galerie' },
    ],
    deletePath: (id) => `/images/${id}`,
  },
  {
    key: 'modifications',
    label: 'Modifications',
    subtitle: 'Demandes de correction',
    endpoint: '/modifications',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'objet_id', label: 'Objet', type: 'select', required: true, optionsKey: 'objets' },
      { name: 'change', label: 'Changement', type: 'textarea', required: true },
      { name: 'confirm', label: 'Confirmé', type: 'boolean' },
    ],
    deletePath: (id) => `/modifications/${id}`,
  },
  {
    key: 'promesses',
    label: 'Promesses',
    subtitle: 'Récompenses associées',
    endpoint: '/promesses',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'objet_id', label: 'Objet', type: 'select', required: true, optionsKey: 'objets' },
      { name: 'montant', label: 'Montant', type: 'number', required: true },
      { name: 'pourcentage_frais', label: 'Frais (%)', type: 'number', required: true },
    ],
    deletePath: (id) => `/promesses/${id}`,
  },
  {
    key: 'temoignages',
    label: 'Temoignages',
    subtitle: 'Retours utilisateurs',
    endpoint: '/temoignages',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'objet_id', label: 'Objet', type: 'select', required: true, optionsKey: 'objets' },
      { name: 'contenu', label: 'Contenu', type: 'textarea', required: true },
    ],
    deletePath: (id) => `/temoignages/${id}`,
  },
  {
    key: 'commissariats',
    label: 'Commissariats',
    subtitle: 'Points de prise en charge',
    endpoint: '/commissariats',
    creatable: true,
    editable: true,
    deletable: true,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'adresse', label: 'Adresse', type: 'textarea' },
      { name: 'latitude', label: 'Latitude', type: 'number', required: true },
      { name: 'longitude', label: 'Longitude', type: 'number', required: true },
    ],
    deletePath: (id) => `/commissariats/${id}`,
  },
  {
    key: 'permissions',
    label: 'Permissions',
    subtitle: 'Autorisations RBAC',
    endpoint: '/rbac/permissions',
    creatable: true,
    editable: false,
    deletable: false,
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
];

export const getAdminResource = (key: string) =>
  ADMIN_RESOURCES.find((resource) => resource.key === key);
